### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by taslimalimi** [glad-tidings/DragonzLandBot#1]
Hello, please show simple command to run this script. Thanks 🙏

**Comment by glad-tidings** [comment]
Hi, I wrote how to use it in the readme

**Comment by AntiWarforever** [comment]
> Hello, please show simple command to run this script. Thanks 🙏

Unfortunately, it doesn't give correct guidance at all, and in the readme file just say dl visual studio, this is need to compile before start & in addition to running it based on a query, you need restore querys every day
