### ISSUE TITLE
System.ArgumentNullException: 'Value cannot be null. Arg_ParamName_Name'

### ISSUE THREAD

**Issue by jason866695** [glad-tidings/DragonzLandBot#2]
As title,in program.cs,line57,how can i fix it,thank you!

**Comment by Lastnet0709** [comment]
If you only need auto click, just turn off or delete this function 😂
![image](https://github.com/user-attachments/assets/c9be5255-3e88-4a39-960f-eaae8b843fea)

**Comment by glad-tidings** [comment]
use new version
https://github.com/glad-tidings/DragonzLandBot-New
